# Generated by Django 4.2.20 on 2025-04-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='treningi.exercise'),
        ),
    ]
