# Generated by Django 4.2.20 on 2025-06-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration',
            field=models.IntegerField(default=1, help_text='Czas trwania w dniach'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treningi.exercise'),
        ),
    ]
