# Generated by Django 4.2.20 on 2025-04-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0002_workout_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, to='treningi.musclegroup'),
        ),
    ]
