# Generated by Django 4.2.20 on 2025-06-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0002_challenge_duration_challenge_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='exercise',
        ),
    ]
