# Generated by Django 4.2.20 on 2025-04-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0003_musclegroup_exercise_muscle_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Podaj ciężar w kilogramach', max_digits=6, null=True),
        ),
    ]
