# Generated by Django 4.2.20 on 2025-06-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0003_remove_challenge_exercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeExercise',
        ),
    ]
