# Generated by Django 4.2.20 on 2025-04-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0005_challenge_custom_exercise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='custom_exercise_description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='custom_exercise_name',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='custom_exercise_weight',
        ),
    ]
