# Generated by Django 5.2 on 2025-05-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0006_remove_challenge_custom_exercise_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='score_xp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/exercises/'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/workouts/'),
        ),
    ]
