# Generated by Django 5.2 on 2025-05-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0007_workout_score_xp_alter_exercise_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_score_xp',
            field=models.IntegerField(default=0),
        ),
    ]
