# Generated by Django 5.2 on 2025-05-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0008_user_user_score_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workouts_history',
            field=models.ManyToManyField(blank=True, to='treningi.workout'),
        ),
    ]
