# Generated by Django 5.2 on 2025-06-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treningi', '0009_user_workouts_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workouts_history',
        ),
    ]
